### ISSUE TITLE
Eve watch with installer

### ISSUE THREAD

**Issue by cblanquera** [Sterling-Technologies/evejs#15]
if someone calls eve watch in an empty folder this should trigger eve install and then start watching.

**Comment by ianmuninio** [comment]
c9e840000872df6e0171b9b646759bba3ebe6367 Merging to develop branch

7c4def433a12cabf332207292bc73c716404e4fc Additional feature: Start server using `nodemon` https://github.com/remy/nodemon
Add on build.json server config nodemon. `"server" : { "nodemon" : { ... } ... }`

afd49eb3eca53c09b26388631b70417e85188870 `eve install` will automatically triggered if no `build.json` file exist on `eve watch`.
