### ISSUE TITLE
Address User Package

### ISSUE THREAD

**Issue by cblanquera** [Sterling-Technologies/evejs#9]
Default build out for how a address relates to a user. You may modify address and user packages to generically accept relational join data and render data with mongoose populate. This should only be a control package.

![a-u](https://cloud.githubusercontent.com/assets/120378/3653973/d5d438f8-115f-11e4-8621-3f4900d6f47a.png)

**Comment by cjzamora** [comment]
Done with Address book, cut off codes by almost 50%, make everything and simple, and also uniform with other joining pattern.

<a href="https://github.com/Openovate/evejs/commit/2eac7fb80d1377af6aee5823f4c2da9a0d6b1b91">Latest Commit for Address-User</a>
